### ISSUE TITLE
Save dialog does not suggest filename of the opened file

### ISSUE THREAD

**Issue by pkrause1980** [flathub/org.avidemux.Avidemux#14]
STEPS TO REPRODUCE
1. File -> Open & open some video file
2. File -> Save

OBSERVED RESULT
"File Name" field of the save dialog is empty

EXPECTED RESULT
"File Name" field of the save dialog is prefilled with the filename of the opened file

ADDITIONAL INFORMATION
1. Works as expected, not an issue, with the appimage and build from source.
2. The outcome is independent from the filesystem permission (via override or manifest) to the directory of the opened file.
3. The titlebar of the avidemux window still knows about the filename of the opened file.
4. Likely due to the use of the file chooser portal, so likely patching the avidemux source code is needed.?

Thanks a lot!

**Comment by pkrause1980** [comment]
The relevant call is happening at avidemux/qt4/ADM_userInterfaces/ADM_gui/file_qt4.cpp, in the function fileSelWriteInternal.
It is QFileDialog::getSaveFileName, and the passed arguments are correct (checked with gdb).

The SaveFile dbus message to the desktop-portal has no "current_name", just "current_file".

The question is should that be set by getSaveFileName (I'd think no, according to the documentation). If yes, that is an upstream issue. If no, then the solution is to find way with Qt to set it and patch that into the Avidemux source.

**Comment by guihkx** [comment]
I think this is the same scenario as I've written in this comment: https://github.com/flathub/org.avidemux.Avidemux/issues/22#issuecomment-2002143119

Summarizing, the KDE and GNOME FileChooser portals will set the filename correctly. The GTK portal, will not.

@pkrause1980  Can you please confirm/revisit this?

**Comment by pkrause1980** [comment]
I did a new test with Kubuntu 23.10.

The filename is prefilled if using xdg-desktop-portal-kde.
Not prefilled if using xdg-desktop-portal-gtk (version 1.14.1-1).

**Comment by pkrause1980** [comment]
Does not appear to be the same issue to me (apart from your comment), but the same cause probably.
The linked issue on the gtk-portal is also about file-extensions.

So maybe I'd need to open a new issue there.
But then, five years and no fix, not very motivating.

**Comment by guihkx** [comment]
I understand your frustration, but unless we introduce a patch here to work around the issue, we'll have to wait for a proper fix in xdg-desktop-portal-gtk.

So I'll close this one, but feel free to send a pull request if you're able to find a workaround.
