### ISSUE TITLE
No 2.8.1 version?

### ISSUE THREAD

**Issue by MikeNavy** [flathub/org.avidemux.Avidemux#15]
Hi,
Avidemux 2.8.1 has been released on 2022-09-23 (see [https://avidemux.sourceforge.net/](url)).

Flatpak version is still 2.8.0.

Is there a problem to have 2.8.1 flatpak?

Regards,

MN

**Comment by ulfi** [comment]
Still no update at the flathub Version :-(
https://flathub.org/apps/details/org.avidemux.Avidemux

**Comment by pkrause1980** [comment]
Pull request #16 has a build of 2.8.1, I expect it to vanish however at some time.
I'd guess testing it is welcome too.
