### ISSUE TITLE
Avidemux icon is incorrect on KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [flathub/org.avidemux.Avidemux#2]
Hi

As we can see in the screenshot below, Avidemux shows Wayland generic icon 
in the title bar and in the task manager. The same icon appears in the task switcher when I press alt+tab.

![avidemux](https://user-images.githubusercontent.com/15967631/55002063-b0c63c80-4fb4-11e9-850b-aa996e0efa5f.png)

**Comment by eszlari** [comment]
You should report that upstream: http://avidemux.org
