### ISSUE TITLE
Avidemux flatpak version doesn't shows up in "Open with" Nautilus dialog box

### ISSUE THREAD

**Issue by antistress** [flathub/org.avidemux.Avidemux#3]
Hi,
I've installed several flatpak application : VLC, Pitivi...
They all show up in "Open with" Nautilus dialog box except Avidemux.

Thanks

Debian 64 bits Sid with GNOME-X11

**Comment by eszlari** [comment]
What file type? Looking at https://github.com/mean00/avidemux2/blob/master/avidemux/qt4/xdg_data/org.avidemux.Avidemux.desktop , one can see there some mimetypes missing (mkv, ts).

**Comment by antistress** [comment]
Interesting.
Indee I tried with a mkv file which is not listed.
But, I've just tried with a mp3 sound and a mpg video and Avidemux doesn't appear either in "Open with" Nautilus dialog box whereas they are both listed

**Comment by eszlari** [comment]
> But, I've just tried with a mp3 sound, a mpg video and a quicktime mp4 video, and Avidemux doesn't appear either in "Open with" Nautilus dialog box,

mp3 and mpg works here (Kubuntu 19.04), mp4 is not in the .desktop file.

So it must be a problem with GNOME or your distro.

**Comment by antistress** [comment]
Hi, I'd like to re-open that bug :
- My problem is still there.
- And my /var/lib/flatpak/exports/share/applications/org.avidemux.Avidemux.desktop is quite different than the one you pointed in your comment (https://github.com/mean00/avidemux2/blob/master/avidemux/qt4/xdg_data/org.avidemux.Avidemux.desktop)

Here is my org.avidemux.Avidemux.desktop :
`Name=Avidemux
GenericName=Video Editor
Comment=Multiplatform video editor
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=avidemux3_qt5 org.avidemux.Avidemux
MimeType=video/mpeg;video/quicktime;video/x-msvideo;video/x-anim;audio/x-mp3;audio/x-mp2;
Icon=org.avidemux.Avidemux
Terminal=false
Type=Application
Categories=AudioVideo
X-Flatpak=org.avidemux.Avidemux`

My avidemux flatpak is up to date from flathub (version 2.7.4)

Thanks !

**Comment by antistress** [comment]
Hi again,
I've modified my /var/lib/flatpak/exports/share/applications/org.avidemux.Avidemux.desktop so that, regading MimeType & Categories, it looks like https://github.com/mean00/avidemux2/blob/master/avidemux/qt4/xdg_data/org.avidemux.Avidemux.desktop.
Then I've restarted my system.
But nothing has changed.

Moreover, I'd like to point out that Avidemux doesn't even shows itself even if I expand the applications list ("View All Applications" button)
I tried with avi, mkv and mp4 files.

Thanks !

**Comment by antistress** [comment]
Also, Avidemux is not listed in /usr/share/applications/mimeapps.list
Could it be the problem ?

I've run update-mime-database /usr/share/mime ans it didn't solve the problem.

Reference :
https://help.gnome.org/admin/system-admin-guide/stable/mime-types-application-user.html.en
https://developer.gnome.org/integration-guide/stable/mime.html.en

Thanks

**Comment by eszlari** [comment]
This has been fixed upstream already: https://github.com/mean00/avidemux2/commit/f4fcab5c11ec7621be004f9c6d59ff79d6cb05ab

In the mean time, i have added a fix in: https://github.com/flathub/org.avidemux.Avidemux/commit/7875aeb6fb246cc906d1bf7100c2de4d1d606bd7

**Comment by antistress** [comment]
> This has been fixed upstream already: [mean00/avidemux2@f4fcab5](https://github.com/mean00/avidemux2/commit/f4fcab5c11ec7621be004f9c6d59ff79d6cb05ab)
> 
> In the meantime, I have added a fix in: [7875aeb](https://github.com/flathub/org.avidemux.Avidemux/commit/7875aeb6fb246cc906d1bf7100c2de4d1d606bd7)

Thank you very much :)

**Comment by antistress** [comment]
I confirm that recent update fixes the bug, with that precision :
For .mkv or .avi files, Avidemux shows up directly (as a recommended application) in "Open with" Nautilus dialog box, whereas for .mp4 file, I had to select "show other applications" since Avidemux was then not part of recommended applications
Thanks
