### ISSUE TITLE
Flatpak version comes with KDE runtime, whereas deb version only relies on Qt

### ISSUE THREAD

**Issue by antistress** [flathub/org.avidemux.Avidemux#4]
Hi,
I used to run Avidemux from deb-multimedia.org ; it relies only on Qt libraries, see https://www.deb-multimedia.org/dists/unstable/main/binary-amd64/package/avidemux-qt.
Whereas Flatpak version relies on KDE runtime.
Is it necessary ?
Thanks

**Comment by eszlari** [comment]
There are basically only three runtimes:

* freedesktop
* GNOME
* KDE

All Qt based apps are using the KDE runtime, so all storage and bandwidth expenditures are shared. It would not be worth the maintenance effort to provide a separate Qt runtime.

**Comment by antistress** [comment]
Ok, thanks !
