### ISSUE TITLE
Add XviD codec

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.avidemux.Avidemux#6]

**Comment by eszlari** [comment]
Why? The codec is obsolete and ffmpeg has it's own MPEG4 encoder.

**Comment by gav-** [comment]
I second this request to include Xvid. I have been unable to produce a compatible ASP stream for some old hardware using the current flathub build.

Xvid was considered to be the superior quality encoder in it's time, I don't believe libav ever matched it. Definitely not obsolete.

**Comment by eszlari** [comment]
fixed: https://github.com/flathub/org.avidemux.Avidemux/pull/10
