### ISSUE TITLE
Blank preview window on Wayland

### ISSUE THREAD

**Issue by antistress** [flathub/org.avidemux.Avidemux#8]
Hi,

Using latest Flatpak version (2.7.4) on GNOME-Wayland,
Avidemux is unusable since the preview window is either blank or almost blank (sometimes a little piece of the video is displayed - see screenshots attached)

Tried on GNOME-X11 and the bug doesn't occur.

Thanks

(Can't compare with the distro version since Debian doesn't have avidemux in their repos)

![capture2](https://user-images.githubusercontent.com/2436957/78613063-5ebc2600-785a-11ea-834b-55a707ed9176.png)
![capture1](https://user-images.githubusercontent.com/2436957/78613091-6d0a4200-785a-11ea-901a-65fbe4dc1cb2.png)

**Comment by TingPing** [comment]
Sounds like an upstream bug, either for Avidemux or Qt.

**Comment by antistress** [comment]
I'm not sure : have you committed a fix or should I report the bug upstream ?

**Comment by antistress** [comment]
OMG I've just got the update and bug is now already fixed !
Thanks you :)

**Comment by eszlari** [comment]
It's not really fixed. Wayland not working should be reported upstream, but they don't have a bug tracker unfortunately.

**Comment by antistress** [comment]
> It's not really fixed. Wayland not working should be reported upstream, but they don't have a bug tracker unfortunately.

Well it's fixed for me since yesterday update..!

**Comment by plata** [comment]
For reference for anybody who reads this because their non-Flatpak version still doesn't have a working preview on Wayland: Force XWayland by setting the environment `QT_QPA_PLATFORM=xcb` or `WAYLAND_DISPLAY=0`.

**Comment by nikicat** [comment]
Hello, did anybody find a fix (not a workaround)?

**Comment by steven-ellis** [comment]
Issue still occurs on Fedora 40 with Wayland and release

- avidemux-qt-2.8.1-4.fc40.x86_64
